language: go
go:
  - 1.10.1
before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -v -race -covermode=atomic -coverprofile=coverage.out ./typetalk/...
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service travis-ci